resource "airbyte_source_definition" "my_sourcedefinition" {
  cpu_limit         = "...my_cpu_limit..."
  cpu_request       = "...my_cpu_request..."
  docker_image_tag  = "...my_docker_image_tag..."
  docker_repository = "...my_docker_repository..."
  documentation_url = "http://jam-packed-guarantee.com"
  icon              = "...my_icon..."
  job_type          = "connection_updater"
  memory_limit      = "...my_memory_limit..."
  memory_request    = "...my_memory_request..."
  name              = "Garrett Kirlin"
  scope_id          = "0b17eae1-dd9c-4435-827c-42c7cd806319"
  scope_type        = "workspace"
  workspace_id      = "46c84086-3d9d-4143-8d46-88b60221d5f1"
}