// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/aballiet/terraform-provider-airbyte/internal/sdk/pkg/types"
	"github.com/aballiet/terraform-provider-airbyte/internal/sdk/pkg/utils"
)

type ActorDefinitionBreakingChange struct {
	Version                   string     `json:"version"`
	Message                   string     `json:"message"`
	UpgradeDeadline           types.Date `json:"upgradeDeadline"`
	MigrationDocumentationURL string     `json:"migrationDocumentationUrl"`
}

func (a ActorDefinitionBreakingChange) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *ActorDefinitionBreakingChange) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ActorDefinitionBreakingChange) GetVersion() string {
	if o == nil {
		return ""
	}
	return o.Version
}

func (o *ActorDefinitionBreakingChange) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}

func (o *ActorDefinitionBreakingChange) GetUpgradeDeadline() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.UpgradeDeadline
}

func (o *ActorDefinitionBreakingChange) GetMigrationDocumentationURL() string {
	if o == nil {
		return ""
	}
	return o.MigrationDocumentationURL
}
