// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AttemptNormalizationStatusReadList struct {
	AttemptNormalizationStatuses []AttemptNormalizationStatusRead `json:"attemptNormalizationStatuses,omitempty"`
}

func (o *AttemptNormalizationStatusReadList) GetAttemptNormalizationStatuses() []AttemptNormalizationStatusRead {
	if o == nil {
		return nil
	}
	return o.AttemptNormalizationStatuses
}
