// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectorBuilderProjectDetails struct {
	// Low code CDK manifest JSON object
	DraftManifest *DeclarativeManifest `json:"draftManifest,omitempty"`
	Name          string               `json:"name"`
}
