// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectorDocumentationRead struct {
	Doc string `json:"doc"`
}

func (o *ConnectorDocumentationRead) GetDoc() string {
	if o == nil {
		return ""
	}
	return o.Doc
}
