// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ConnectionScheduleType - determine how the schedule data should be interpreted
type ConnectionScheduleType string

const (
	ConnectionScheduleTypeManual ConnectionScheduleType = "manual"
	ConnectionScheduleTypeBasic  ConnectionScheduleType = "basic"
	ConnectionScheduleTypeCron   ConnectionScheduleType = "cron"
)

func (e ConnectionScheduleType) ToPointer() *ConnectionScheduleType {
	return &e
}

func (e *ConnectionScheduleType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "manual":
		fallthrough
	case "basic":
		fallthrough
	case "cron":
		*e = ConnectionScheduleType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ConnectionScheduleType: %v", v)
	}
}
