// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ConnectionReadList - Successful operation
type ConnectionReadList struct {
	Connections []ConnectionRead `json:"connections"`
}
