// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionJobRequestBody struct {
	ConnectionID string `json:"connectionId"`
	JobID        int64  `json:"jobId"`
}

func (o *ConnectionJobRequestBody) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *ConnectionJobRequestBody) GetJobID() int64 {
	if o == nil {
		return 0
	}
	return o.JobID
}
