// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionSyncProgressReadItem struct {
	StreamName             string `json:"streamName"`
	StreamNamespace        string `json:"streamNamespace"`
	RecordsExtracted       int64  `json:"recordsExtracted"`
	RecordsLoaded          int64  `json:"recordsLoaded"`
	SyncTimeElapsed        int64  `json:"syncTimeElapsed"`
	ProgressPercentage     int    `json:"progressPercentage"`
	LastCommittedTimestamp int64  `json:"lastCommittedTimestamp"`
	LastCursorValue        string `json:"lastCursorValue"`
}

func (o *ConnectionSyncProgressReadItem) GetStreamName() string {
	if o == nil {
		return ""
	}
	return o.StreamName
}

func (o *ConnectionSyncProgressReadItem) GetStreamNamespace() string {
	if o == nil {
		return ""
	}
	return o.StreamNamespace
}

func (o *ConnectionSyncProgressReadItem) GetRecordsExtracted() int64 {
	if o == nil {
		return 0
	}
	return o.RecordsExtracted
}

func (o *ConnectionSyncProgressReadItem) GetRecordsLoaded() int64 {
	if o == nil {
		return 0
	}
	return o.RecordsLoaded
}

func (o *ConnectionSyncProgressReadItem) GetSyncTimeElapsed() int64 {
	if o == nil {
		return 0
	}
	return o.SyncTimeElapsed
}

func (o *ConnectionSyncProgressReadItem) GetProgressPercentage() int {
	if o == nil {
		return 0
	}
	return o.ProgressPercentage
}

func (o *ConnectionSyncProgressReadItem) GetLastCommittedTimestamp() int64 {
	if o == nil {
		return 0
	}
	return o.LastCommittedTimestamp
}

func (o *ConnectionSyncProgressReadItem) GetLastCursorValue() string {
	if o == nil {
		return ""
	}
	return o.LastCursorValue
}
