// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomDestinationDefinitionCreate struct {
	DestinationDefinition DestinationDefinitionCreate `json:"destinationDefinition"`
	WorkspaceID           string                      `json:"workspaceId"`
}
