// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomSourceDefinitionCreate struct {
	SourceDefinition SourceDefinitionCreate `json:"sourceDefinition"`
	WorkspaceID      string                 `json:"workspaceId"`
}
