// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeclarativeManifestsReadList - Successful operation
type DeclarativeManifestsReadList struct {
	ManifestVersions []DeclarativeManifestVersionRead `json:"manifestVersions"`
}
