// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DestinationDefinitionReadList struct {
	DestinationDefinitions []DestinationDefinitionRead `json:"destinationDefinitions"`
}

func (o *DestinationDefinitionReadList) GetDestinationDefinitions() []DestinationDefinitionRead {
	if o == nil {
		return []DestinationDefinitionRead{}
	}
	return o.DestinationDefinitions
}
