// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DestinationDefinitionSpecification - The specification for what values are required to configure the destinationDefinition.
type DestinationDefinitionSpecification struct {
}
