// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DestinationSnippetRead struct {
	DestinationDefinitionID string  `json:"destinationDefinitionId"`
	DestinationID           string  `json:"destinationId"`
	DestinationName         string  `json:"destinationName"`
	Icon                    *string `json:"icon,omitempty"`
	Name                    string  `json:"name"`
}
