// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type InternalOperationResult struct {
	Succeeded bool `json:"succeeded"`
}

func (o *InternalOperationResult) GetSucceeded() bool {
	if o == nil {
		return false
	}
	return o.Succeeded
}
