// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type InvalidInputProperty struct {
	InvalidValue *string `json:"invalidValue,omitempty"`
	Message      *string `json:"message,omitempty"`
	PropertyPath string  `json:"propertyPath"`
}
