// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListOrganizationsByUserRequestBody struct {
	UserID       string      `json:"userId"`
	Pagination   *Pagination `json:"pagination,omitempty"`
	NameContains *string     `json:"nameContains,omitempty"`
}

func (o *ListOrganizationsByUserRequestBody) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

func (o *ListOrganizationsByUserRequestBody) GetPagination() *Pagination {
	if o == nil {
		return nil
	}
	return o.Pagination
}

func (o *ListOrganizationsByUserRequestBody) GetNameContains() *string {
	if o == nil {
		return nil
	}
	return o.NameContains
}
