// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ListDeclarativeManifestsRequestBody struct {
	WorkspaceID        string `json:"workspaceId"`
	SourceDefinitionID string `json:"sourceDefinitionId"`
}

func (o *ListDeclarativeManifestsRequestBody) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *ListDeclarativeManifestsRequestBody) GetSourceDefinitionID() string {
	if o == nil {
		return ""
	}
	return o.SourceDefinitionID
}
