// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// OperationRead - Successful operation
type OperationRead struct {
	Name                  string                `json:"name"`
	OperationID           string                `json:"operationId"`
	OperatorConfiguration OperatorConfiguration `json:"operatorConfiguration"`
	WorkspaceID           string                `json:"workspaceId"`
}
