// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type OperatorType string

const (
	OperatorTypeNormalization OperatorType = "normalization"
	OperatorTypeDbt           OperatorType = "dbt"
	OperatorTypeWebhook       OperatorType = "webhook"
)

func (e OperatorType) ToPointer() *OperatorType {
	return &e
}

func (e *OperatorType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "normalization":
		fallthrough
	case "dbt":
		fallthrough
	case "webhook":
		*e = OperatorType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for OperatorType: %v", v)
	}
}
