// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrganizationIDRequestBody struct {
	OrganizationID string `json:"organizationId"`
}

func (o *OrganizationIDRequestBody) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}
