// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrganizationUserReadList struct {
	Users []OrganizationUserRead `json:"users"`
}

func (o *OrganizationUserReadList) GetUsers() []OrganizationUserRead {
	if o == nil {
		return []OrganizationUserRead{}
	}
	return o.Users
}
