// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PermissionUpdate struct {
	PermissionID string `json:"permissionId"`
	// Describes what actions/endpoints the permission entitles to
	PermissionType *PermissionType `json:"permissionType,omitempty"`
}

func (o *PermissionUpdate) GetPermissionID() string {
	if o == nil {
		return ""
	}
	return o.PermissionID
}

func (o *PermissionUpdate) GetPermissionType() *PermissionType {
	if o == nil {
		return nil
	}
	return o.PermissionType
}
