// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PrivateSourceDefinitionReadList - Successful operation
type PrivateSourceDefinitionReadList struct {
	SourceDefinitions []PrivateSourceDefinitionRead `json:"sourceDefinitions"`
}
