// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PrivateSourceDefinitionReadList struct {
	SourceDefinitions []PrivateSourceDefinitionRead `json:"sourceDefinitions"`
}

func (o *PrivateSourceDefinitionReadList) GetSourceDefinitions() []PrivateSourceDefinitionRead {
	if o == nil {
		return []PrivateSourceDefinitionRead{}
	}
	return o.SourceDefinitions
}
