// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ResourceRequirements - optional resource requirements to run workers (blank for unbounded allocations)
type ResourceRequirements struct {
	CPURequest    *string `json:"cpu_request,omitempty"`
	CPULimit      *string `json:"cpu_limit,omitempty"`
	MemoryRequest *string `json:"memory_request,omitempty"`
	MemoryLimit   *string `json:"memory_limit,omitempty"`
}

func (o *ResourceRequirements) GetCPURequest() *string {
	if o == nil {
		return nil
	}
	return o.CPURequest
}

func (o *ResourceRequirements) GetCPULimit() *string {
	if o == nil {
		return nil
	}
	return o.CPULimit
}

func (o *ResourceRequirements) GetMemoryRequest() *string {
	if o == nil {
		return nil
	}
	return o.MemoryRequest
}

func (o *ResourceRequirements) GetMemoryLimit() *string {
	if o == nil {
		return nil
	}
	return o.MemoryLimit
}
