// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SetInstancewideDestinationOauthParamsRequestBody struct {
	DestinationDefinitionID string                 `json:"destinationDefinitionId"`
	Params                  map[string]interface{} `json:"params"`
}
