// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SourceSnippetRead struct {
	Icon               *string `json:"icon,omitempty"`
	Name               string  `json:"name"`
	SourceDefinitionID string  `json:"sourceDefinitionId"`
	SourceID           string  `json:"sourceId"`
	SourceName         string  `json:"sourceName"`
}
