// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// SourceAutoPropagateChange - Input of the source propagation, it contains the discovered catalog and a list of diff that need to be applied to the existing catalog.
type SourceAutoPropagateChange struct {
	// describes the available schema (catalog).
	Catalog     AirbyteCatalog `json:"catalog"`
	CatalogID   string         `json:"catalogId"`
	SourceID    string         `json:"sourceId"`
	WorkspaceID string         `json:"workspaceId"`
}

func (o *SourceAutoPropagateChange) GetCatalog() AirbyteCatalog {
	if o == nil {
		return AirbyteCatalog{}
	}
	return o.Catalog
}

func (o *SourceAutoPropagateChange) GetCatalogID() string {
	if o == nil {
		return ""
	}
	return o.CatalogID
}

func (o *SourceAutoPropagateChange) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *SourceAutoPropagateChange) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}
