// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SourceDefinitionIDWithWorkspaceID struct {
	SourceDefinitionID string `json:"sourceDefinitionId"`
	WorkspaceID        string `json:"workspaceId"`
}
