// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SourceCoreConfig struct {
	// The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
	ConnectionConfiguration interface{} `json:"connectionConfiguration"`
	SourceDefinitionID      string      `json:"sourceDefinitionId"`
	SourceID                *string     `json:"sourceId,omitempty"`
	WorkspaceID             string      `json:"workspaceId"`
}
