// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// StreamStatusReadList - Successfully queried stream statuses.
type StreamStatusReadList struct {
	StreamStatuses []StreamStatusRead `json:"streamStatuses,omitempty"`
}
