// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type StreamState struct {
	StreamDescriptor StreamDescriptor `json:"streamDescriptor"`
	StreamState      *StateBlob       `json:"streamState,omitempty"`
}
