// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type StreamStatusJobType string

const (
	StreamStatusJobTypeSync  StreamStatusJobType = "SYNC"
	StreamStatusJobTypeReset StreamStatusJobType = "RESET"
)

func (e StreamStatusJobType) ToPointer() *StreamStatusJobType {
	return &e
}

func (e *StreamStatusJobType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SYNC":
		fallthrough
	case "RESET":
		*e = StreamStatusJobType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StreamStatusJobType: %v", v)
	}
}
