// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type StreamTransformTransformType string

const (
	StreamTransformTransformTypeAddStream    StreamTransformTransformType = "add_stream"
	StreamTransformTransformTypeRemoveStream StreamTransformTransformType = "remove_stream"
	StreamTransformTransformTypeUpdateStream StreamTransformTransformType = "update_stream"
)

func (e StreamTransformTransformType) ToPointer() *StreamTransformTransformType {
	return &e
}

func (e *StreamTransformTransformType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "add_stream":
		fallthrough
	case "remove_stream":
		fallthrough
	case "update_stream":
		*e = StreamTransformTransformType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StreamTransformTransformType: %v", v)
	}
}

type StreamTransform struct {
	StreamDescriptor StreamDescriptor             `json:"streamDescriptor"`
	TransformType    StreamTransformTransformType `json:"transformType"`
	// list of field transformations. order does not matter.
	UpdateStream []FieldTransform `json:"updateStream,omitempty"`
}
