// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type SyncMode string

const (
	SyncModeFullRefresh SyncMode = "full_refresh"
	SyncModeIncremental SyncMode = "incremental"
)

func (e SyncMode) ToPointer() *SyncMode {
	return &e
}

func (e *SyncMode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "full_refresh":
		fallthrough
	case "incremental":
		*e = SyncMode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SyncMode: %v", v)
	}
}
