// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskQueueNameRead struct {
	// Name of the temporal task queue.
	TaskQueueName string `json:"taskQueueName"`
}

func (o *TaskQueueNameRead) GetTaskQueueName() string {
	if o == nil {
		return ""
	}
	return o.TaskQueueName
}
