// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebBackendOperationCreateOrUpdate struct {
	Name                  string                `json:"name"`
	OperationID           *string               `json:"operationId,omitempty"`
	OperatorConfiguration OperatorConfiguration `json:"operatorConfiguration"`
	WorkspaceID           string                `json:"workspaceId"`
}
