// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebBackendGeographiesListResult struct {
	Geographies []Geography `json:"geographies"`
}

func (o *WebBackendGeographiesListResult) GetGeographies() []Geography {
	if o == nil {
		return []Geography{}
	}
	return o.Geographies
}
