// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WebBackendConnectionRequestBody struct {
	WithRefreshedCatalog *bool  `json:"withRefreshedCatalog,omitempty"`
	ConnectionID         string `json:"connectionId"`
}

func (o *WebBackendConnectionRequestBody) GetWithRefreshedCatalog() *bool {
	if o == nil {
		return nil
	}
	return o.WithRefreshedCatalog
}

func (o *WebBackendConnectionRequestBody) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}
