// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceOrganizationInfoRead - Limited info about a workspace's organization that is safe to expose to workspace readers who are not members of the org.
type WorkspaceOrganizationInfoRead struct {
	OrganizationID   string `json:"organizationId"`
	OrganizationName string `json:"organizationName"`
	Pba              bool   `json:"pba"`
	Sso              bool   `json:"sso"`
}

func (o *WorkspaceOrganizationInfoRead) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *WorkspaceOrganizationInfoRead) GetOrganizationName() string {
	if o == nil {
		return ""
	}
	return o.OrganizationName
}

func (o *WorkspaceOrganizationInfoRead) GetPba() bool {
	if o == nil {
		return false
	}
	return o.Pba
}

func (o *WorkspaceOrganizationInfoRead) GetSso() bool {
	if o == nil {
		return false
	}
	return o.Sso
}
