// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkspaceRead - Successful operation
type WorkspaceRead struct {
	AnonymousDataCollection *bool                 `json:"anonymousDataCollection,omitempty"`
	CustomerID              string                `json:"customerId"`
	DefaultGeography        *Geography            `json:"defaultGeography,omitempty"`
	DisplaySetupWizard      *bool                 `json:"displaySetupWizard,omitempty"`
	Email                   *string               `json:"email,omitempty"`
	FeedbackDone            *bool                 `json:"feedbackDone,omitempty"`
	FirstCompletedSync      *bool                 `json:"firstCompletedSync,omitempty"`
	InitialSetupComplete    bool                  `json:"initialSetupComplete"`
	Name                    string                `json:"name"`
	News                    *bool                 `json:"news,omitempty"`
	NotificationSettings    *NotificationSettings `json:"notificationSettings,omitempty"`
	Notifications           []Notification        `json:"notifications,omitempty"`
	SecurityUpdates         *bool                 `json:"securityUpdates,omitempty"`
	Slug                    string                `json:"slug"`
	WebhookConfigs          []WebhookConfigRead   `json:"webhookConfigs,omitempty"`
	WorkspaceID             string                `json:"workspaceId"`
}
