// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type AirbyteStream struct {
	DefaultCursorField      []types.String          `tfsdk:"default_cursor_field"`
	JSONSchema              map[string]types.String `tfsdk:"json_schema"`
	Name                    types.String            `tfsdk:"name"`
	Namespace               types.String            `tfsdk:"namespace"`
	SourceDefinedCursor     types.Bool              `tfsdk:"source_defined_cursor"`
	SourceDefinedPrimaryKey [][]types.String        `tfsdk:"source_defined_primary_key"`
	SupportedSyncModes      []types.String          `tfsdk:"supported_sync_modes"`
}
