// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type OperatorWebhook struct {
	DbtCloud        *DbtCloud    `tfsdk:"dbt_cloud"`
	ExecutionBody   types.String `tfsdk:"execution_body"`
	ExecutionURL    types.String `tfsdk:"execution_url"`
	WebhookConfigID types.String `tfsdk:"webhook_config_id"`
	WebhookType     types.String `tfsdk:"webhook_type"`
}
