// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type WebhookConfigRead struct {
	AuthToken     types.String `tfsdk:"auth_token"`
	ID            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	ValidationURL types.String `tfsdk:"validation_url"`
}
