// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

type ConnectionScheduleData struct {
	BasicSchedule *BasicSchedule `tfsdk:"basic_schedule"`
	Cron          *Cron          `tfsdk:"cron"`
}
