// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type WebhookConfigRead1 struct {
	ID   types.String `tfsdk:"id"`
	Name types.String `tfsdk:"name"`
}
