// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type AirbyteStreamConfiguration struct {
	AliasName             types.String        `tfsdk:"alias_name"`
	CursorField           []types.String      `tfsdk:"cursor_field"`
	DestinationSyncMode   types.String        `tfsdk:"destination_sync_mode"`
	FieldSelectionEnabled types.Bool          `tfsdk:"field_selection_enabled"`
	PrimaryKey            [][]types.String    `tfsdk:"primary_key"`
	Selected              types.Bool          `tfsdk:"selected"`
	SelectedFields        []SelectedFieldInfo `tfsdk:"selected_fields"`
	Suggested             types.Bool          `tfsdk:"suggested"`
	SyncMode              types.String        `tfsdk:"sync_mode"`
}
