// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type StreamTransform struct {
	StreamDescriptor StreamDescriptor `tfsdk:"stream_descriptor"`
	TransformType    types.String     `tfsdk:"transform_type"`
	UpdateStream     []FieldTransform `tfsdk:"update_stream"`
}
