// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type JobTypeResourceLimit struct {
	JobType              types.String         `tfsdk:"job_type"`
	ResourceRequirements ResourceRequirements `tfsdk:"resource_requirements"`
}
