// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type CheckOperationResponse struct {
	// Successful operation
	CheckOperationRead *shared.CheckOperationRead
	ContentType        string
	// Input failed validation
	InvalidInputExceptionInfo *shared.InvalidInputExceptionInfo
	StatusCode                int
	RawResponse               *http.Response
}
