// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/aballiet/terraform-provider-airbyte/internal/sdk/pkg/models/shared"
	"net/http"
)

type WebBackendListGeographiesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	WebBackendGeographiesListResult *shared.WebBackendGeographiesListResult
}

func (o *WebBackendListGeographiesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *WebBackendListGeographiesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *WebBackendListGeographiesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *WebBackendListGeographiesResponse) GetWebBackendGeographiesListResult() *shared.WebBackendGeographiesListResult {
	if o == nil {
		return nil
	}
	return o.WebBackendGeographiesListResult
}
